version: '3.8'

services:
  backend:
    build: 
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - UVICORN_RELOAD=true
    volumes:
      - ./backend/app:/app
    tty: true
    restart: unless-stopped
    networks:
      - shinan-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

networks:
  shinan-network:
    driver: bridge 