import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Shinan Research",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="shinan-body" style={{ minHeight: "100vh", margin: 0 }}>
        <div
          className="shinan-kanji"
          style={{
            position: "fixed",
            top: 16,
            left: "50%",
            transform: "translateX(-50%)",
            zIndex: 100,
            userSelect: "none",
            background: "rgb(255,255,255)",
            border: "3px solid black",
            borderRadius: "16px",
            padding: "0px 12px",
          }}
        >
          指南
        </div>
        {children}
      </body>
    </html>
  );
}
