import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Shinan Research",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="shinan-body" style={{ minHeight: "100vh", margin: 0 }}>
        <div style={{
          position: "fixed",
          top: 24,
          left: 32,
          zIndex: 100,
          fontSize: 32,
          fontWeight: 900,
          color: "#1a3d2f",
          letterSpacing: 2,
          fontFamily: "Noto Sans JP, Segoe UI, Hiragino Sans, Meiryo, sans-serif",
          userSelect: "none",
          textShadow: "0 2px 8px rgba(0,0,0,0.08)"
        }}>
          指南
        </div>
        {children}
      </body>
    </html>
  );
}
